### ISSUE TITLE
Rename compound math functions

### ISSUE THREAD

**Issue by pakim249CAL** [morpho-dao/morpho-utils#21]
There can be potential confusion with the function names of CompoundMath imo. This lib does fixed point mul and div, which is not the behavior of most past usage of mul and div in solidity when both the inputs and outputs are uint256. This can be confusing imo if contracts use `using CompoundMath for uint256`. For readability and to remove any possible confusion, I propose renaming the fns. Some of my ideas:

* cMul/Div
* compMul/Div
* cWadMul
* cWadDiv

**Comment by MathisGD** [comment]
I think that the reason why it has been let like this, is that we wanted this lib to be able to replace without any change Compound's lib. If we want to change the naming now (which might be a good idea), I would go for `wadMul` and `wadDiv`. And I would change the name of the lib for `WadMath`.

**Comment by MathisGD** [comment]
What do you think about switching everything to `rMul`.. `wMul`... etc ?

**Comment by Rubilmax** [comment]
I find `wad` & `ray` prefixes clearer and not that long
Also, we'd be introducing a breaking change

**Comment by MathisGD** [comment]
okok.

note that there is also the rounding at the end: `rayMulDown` ...

**Comment by MerlinEgalite** [comment]
Yep
