### ISSUE TITLE
Comparing greater than against rounded down number

### ISSUE THREAD

**Issue by pakim249CAL** [morpho-dao/morpho-utils#22]
https://github.com/morpho-labs/morpho-utils/blob/edc94386e191c44ec4dc2b596ee5185758febc63/src/math/WadRayMath.sol#L31

The noted comparison compares in solidity against a rounded down number. I don't see either aave or solmate using this kind of comparison, so I'm not sure it's kosher. Might be leaky?

**Comment by MathisGD** [comment]
I think it is equivalent. But we should write something on this you are right, this is not trivial.

**Comment by MathisGD** [comment]
<img width="599" alt="Capture d’écran 2022-10-09 à 20 21 36" src="https://user-images.githubusercontent.com/74971347/194773135-edf38217-ab7c-4ed9-882a-64e6490a5139.png">
