### ISSUE TITLE
Create optimized SafeCast lib

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-dao/morpho-utils#65]
Not possible to have an optimized version: https://github.com/morpho-dao/morpho-utils/pull/70

**Comment by MathisGD** [comment]
Why did you closed it ?

**Comment by Rubilmax** [comment]
Why not closing it, as the issue has been explored and it seems we can't find an optimized version?

**Comment by MerlinEgalite** [comment]
@MathisGD is working on it

**Comment by Rubilmax** [comment]
Please consider that:
- Solmate already worked on this with open-source and realized they could only improve the error-raising part of it (https://github.com/transmissions11/solmate/blob/main/src/utils/SafeCastLib.sol)
- I am deeply convinced it's not worth it considering the check necessary to safe cast a value down (`value <= maxTypeValue`) cannot be optimized as it already compiles to a minimalist series of opcodes (this is what I tried - and failed - to explain [here](https://github.com/morpho-dao/morpho-utils/pull/70#issuecomment-1349031367))

**Comment by MathisGD** [comment]
I did some tests, but nothing beats Solmate's implem, so yes I'm finally closing it.
