### ISSUE TITLE
License Identifier `GNU APGLv3` is not valid: replace with `AGPL-3.0-only`

### ISSUE THREAD

**Issue by Rubilmax** [morpho-dao/morpho-utils#82]
sauce:
- https://spdx.org/licenses/
- https://spdx.org/licenses/AGPL-3.0.html
- https://spdx.org/licenses/AGPL-3.0-only.html

**Comment by MerlinEgalite** [comment]
source no? 😆 I like sauce too though

**Comment by Rubilmax** [comment]
> source no? 😆 I like sauce too though

it's a meme ref you normie
